"""Loturile. Fiecare lot inclina greutatile spre lumea lui, ca sa aiba caracter
propriu; trasaturile raman insa globale, deci raritatea se calculeaza pe toata
colectia, nu pe lot."""

# boost = de cate ori creste greutatea trasaturii in lotul asta
LOTS = [
    dict(
        code='GEN', only={'Suit': ['OG Yellow','Hazard Orange','Bone White','Steel Grey','Deep Teal','Sand'], 'Scene': ['Studio Teal', 'Studio Amber', 'Studio Sand', 'Studio Cream', 'Studio Slate', 'Studio Olive', 'Studio Navy', 'Studio Magenta', 'Studio Plum']}, name='Genesis Run',
        blurb='Originalii. Galben de fabrica, fundal de studio, fara podoabe.',
        share=0.10,
        none=dict(hat=260, item=280, cloth=300, fx=420, badge=200),
        boost=dict(
            Suit={'OG Yellow': 14, 'Hazard Orange': 3},
            Eye={'Red': 8},
            Scene={'Studio Teal': 10, 'Studio Amber': 4, 'Studio Sand': 4,
                   'Studio Cream': 4, 'Studio Slate': 3, 'Studio Olive': 3},
            Badge={'Serial Tag': 4, 'OG Patch': 3},
        )),
    dict(
        code='DEEP', only={'Scene': ['Deep Sea', 'Ice Cave', 'Swamp', 'Orbital Deck', 'Studio Navy', 'Subway']}, name='Deep Run',
        blurb='Sub apa si sub gheata. Aer imprumutat, presiune mare.',
        share=0.10,
        none=dict(hat=26, item=30, cloth=40, fx=24),
        boost=dict(
            Suit={'Deep Teal': 7, 'Cobalt': 6, 'Mint': 5, 'Frozen': 8, 'Slate Blue': 5},
            Eye={'Ice Blue': 6, 'Cyan': 5},
            Scene={'Deep Sea': 9, 'Ice Cave': 8, 'Swamp': 5, 'Orbital Deck': 3},
            Headwear={'Space Dome': 7, 'Bucket Hat': 4, 'Visor': 3},
            **{'Held Item': {'Trident': 8, 'Pickaxe': 7, 'Diamond': 4, 'Lantern': 4}},
            Effect={'Bubbles': 9, 'Snow': 7},
        )),
    dict(
        code='NEON', only={'Scene': ['Neon Alley', 'Cyber Grid', 'Arcade', 'Rooftop Night', 'Subway', 'Studio Magenta']}, name='Neon District',
        blurb='Noaptea in oras. Lumina de reclama si semnal prost.',
        share=0.10,
        none=dict(hat=24, item=28, cloth=36, fx=18),
        boost=dict(
            Suit={'Ultra Violet': 6, 'Bubblegum': 6, 'Neon Wire': 9, 'Glitched': 7, 'Ink': 4},
            Eye={'Violet': 5, 'Cyan': 5},
            Scene={'Neon Alley': 9, 'Cyber Grid': 7, 'Arcade': 6, 'Rooftop Night': 6, 'Subway': 6},
            Headwear={'Cap': 6, 'Visor': 6, 'Headphones': 6, 'Party Hat': 3},
            **{'Held Item': {'Spray Can': 8, 'Joystick': 6, 'Guitar': 5, 'Chain': 4}},
            Outfit={'Puffer Jacket': 5, 'Gold Chains': 5, 'Hawaiian Shirt': 3},
            Effect={'Glitch': 9, 'Scanlines': 6},
        )),
    dict(
        code='PIT', only={'Suit': ['Molten','Rusted','Copper','Hazard Orange','Clay','Sand','Steel Grey','OG Yellow','Blood Red','Camo','Void Black','Crimson'], 'Scene': ['Lava Field', 'Mine Shaft', 'Wasteland', 'Desert Ruins', 'Toxic Lab', 'Studio Amber']}, name='The Pit',
        blurb='Unde se sapa. Caldura, praf si scule.',
        share=0.10,
        none=dict(hat=20, item=22, cloth=28, fx=30),
        boost=dict(
            Suit={'Molten': 8, 'Rusted': 8, 'Copper': 6, 'Hazard Orange': 6, 'Clay': 5},
            Eye={'Amber': 6, 'Red': 4},
            Scene={'Lava Field': 8, 'Mine Shaft': 8, 'Wasteland': 7, 'Desert Ruins': 6},
            Headwear={'Hard Hat': 9, 'Bandana': 5, 'Pith Helmet': 4, 'Beacon': 4},
            **{'Held Item': {'Shovel': 7, 'Pickaxe': 8, 'Wrench': 7, 'Torch': 6, 'Lantern': 5, 'Battle Axe': 4}},
            Outfit={'Hazard Vest': 8, 'Tool Belt': 8, 'Bandolier': 4},
            Effect={'Embers': 9},
            Badge={'Cracked Panel': 5, 'Radiation': 4},
        )),
    dict(
        code='CNCL', only={'Scene': ['Bank Vault', 'Casino Floor', 'Void', 'Studio Plum', 'Desert Ruins', 'Orbital Deck']}, name='High Council',
        blurb='Cei care nu mai muncesc. Aur, catifea si titlu.',
        share=0.09,
        none=dict(hat=10, item=24, cloth=18, fx=40),
        boost=dict(
            Suit={'Solid Gold': 9, 'Marble': 7, 'Void Black': 6, 'Ink': 6, 'Crimson': 5},
            Eye={'Gold': 7, 'Violet': 4, 'Void': 4},
            Scene={'Bank Vault': 8, 'Casino Floor': 7, 'Void': 6, 'Studio Plum': 5},
            Headwear={'Crown': 9, 'Top Hat': 7, 'Laurel': 6, 'Halo': 4},
            **{'Held Item': {'Banner': 6, 'Arcane Staff': 5, 'Money Bag': 6, 'Diamond': 5}},
            Outfit={'Cape': 8, 'Tuxedo': 7, 'Gold Chains': 6},
            Badge={'OG Patch': 6},
        )),
    dict(
        code='FLD', only={'Scene': ['Jungle Temple', 'Greenhouse', 'Swamp', 'Zen Garden', 'Desert Ruins', 'Sky Islands', 'Wasteland']}, name='Field Work',
        blurb='Afara, in verde. Se cara, se sapa, se culege.',
        share=0.10,
        none=dict(hat=18, item=24, cloth=24, fx=44),
        boost=dict(
            Suit={'Overgrown': 8, 'Moss': 7, 'Camo': 7, 'Sand': 6, 'Toxic Green': 5},
            Eye={'Acid Green': 6, 'Amber': 4},
            Scene={'Jungle Temple': 8, 'Greenhouse': 7, 'Swamp': 6, 'Zen Garden': 6,
                   'Desert Ruins': 5, 'Sky Islands': 4},
            Headwear={'Straw Hat': 8, 'Pith Helmet': 7, 'Bucket Hat': 6},
            **{'Held Item': {'Shovel': 7, 'Umbrella': 5, 'Pickaxe': 4, 'Flask': 4}},
            Outfit={'Hazard Vest': 5, 'Backpack': 8, 'Tool Belt': 5, 'Poncho': 6, 'Apron': 4},
        )),
    dict(
        code='CLN', only={'Suit': ['Bone White','Chalk','Chrome','Steel Grey','Mint','Marble','Cobalt','Toxic Green','Circuit','Matrix Code','Slate Blue'], 'Scene': ['Toxic Lab', 'Server Room', 'Orbital Deck', 'Greenhouse', 'Matrix Rain', 'Studio Cream']}, name='Clean Room',
        blurb='Interior steril. Totul se masoara si se noteaza.',
        share=0.10,
        none=dict(hat=30, item=22, cloth=14, fx=40),
        boost=dict(
            Suit={'Bone White': 8, 'Chalk': 7, 'Chrome': 6, 'Steel Grey': 6, 'Mint': 4},
            Eye={'Acid Green': 5, 'Ice Blue': 5, 'Bone': 4},
            Scene={'Toxic Lab': 8, 'Server Room': 7, 'Orbital Deck': 6, 'Greenhouse': 4},
            Headwear={'Space Dome': 6, 'Beacon': 5, 'Visor': 4},
            **{'Held Item': {'Flask': 8, 'Briefcase': 6, 'Wrench': 5}},
            Outfit={'Lab Coat': 9, 'Medic Suit': 8, 'Apron': 4},
            Effect={'Radiation': 6, 'Sparks': 5},
            Badge={'Biohazard': 6, 'Serial Tag': 5, 'Circuit Plate': 4},
        )),
    dict(
        code='WAR', only={'Scene': ['Cyber Grid', 'Desert Ruins', 'Rooftop Night', 'Void', 'Wasteland', 'Mine Shaft', 'Jungle Temple']}, name='Warband',
        blurb='Se iese cu lama la vedere. Nu intreaba nimeni de ce.',
        share=0.10,
        none=dict(hat=14, item=12, cloth=22, fx=44),
        boost=dict(
            Suit={'Blood Red': 7, 'Crimson': 7, 'Void Black': 6, 'Steel Grey': 5, 'Rusted': 4},
            Eye={'Red': 6, 'Amber': 4, 'Void': 4},
            Scene={'Cyber Grid': 6, 'Desert Ruins': 6, 'Rooftop Night': 6, 'Void': 5,
                   'Wasteland': 5},
            Headwear={'Kabuto': 8, 'Pirate Tricorn': 7, 'Viking Helm': 8, 'Horns': 6,
                      'Bandana': 4},
            **{'Held Item': {'Katana': 8, 'Cutlass': 7, 'Battle Axe': 7, 'Scythe': 6,
                             'Baseball Bat': 5, 'Trident': 3}},
            Outfit={'Armor': 9, 'Bandolier': 7, 'Cape': 5},
        )),
    dict(
        code='OFF', only={'Scene': ['Matrix Rain', 'Void', 'Orbital Deck', 'Cyber Grid', 'Server Room', 'Subway']}, name='Off Grid',
        blurb='Iesit din sistem. Semnalul il tine altcineva.',
        share=0.10,
        none=dict(hat=40, item=44, cloth=52, fx=14),
        boost=dict(
            Suit={'Matrix Code': 9, 'Cosmic': 8, 'Circuit': 8, 'Glitched': 7, 'Neon Wire': 5},
            Eye={'Acid Green': 6, 'Cyan': 5, 'Void': 5},
            Scene={'Matrix Rain': 9, 'Void': 7, 'Orbital Deck': 6, 'Cyber Grid': 5},
            Headwear={'Beacon': 6, 'Halo': 5, 'Space Dome': 5},
            **{'Held Item': {'Diamond': 5, 'Chain': 5, 'Arcane Staff': 4}},
            Effect={'Glitch': 8, 'Radiation': 6, 'Scanlines': 5},
            Badge={'Circuit Plate': 6, 'Cracked Panel': 4},
        )),
    dict(
        code='AFT', only={'Scene': ['Arcade', 'Casino Floor', 'Rooftop Night', 'Sky Islands', 'Studio Magenta', 'Studio Navy', 'Zen Garden']}, name='After Hours',
        blurb='Gata cu tura. Se bea, se joaca, se face galagie.',
        share=0.11,
        none=dict(hat=22, item=26, cloth=30, fx=40),
        boost=dict(
            Suit={'Bubblegum': 7, 'Mint': 6, 'Denim': 8, 'Slate Blue': 5, 'Clay': 4},
            Eye={'Violet': 4, 'Amber': 4, 'Cyan': 4},
            Scene={'Arcade': 8, 'Casino Floor': 7, 'Rooftop Night': 6, 'Sky Islands': 6,
                   'Studio Magenta': 4, 'Studio Navy': 4},
            Headwear={'Party Hat': 8, 'Beret': 6, 'Headphones': 7, 'Bucket Hat': 5,
                      'Cowboy Hat': 4},
            **{'Held Item': {'Joystick': 7, 'Guitar': 7, 'Baseball Bat': 5, 'Umbrella': 5,
                             'Frying Pan': 4}},
            Outfit={'Hawaiian Shirt': 8, 'Puffer Jacket': 6, 'Gold Chains': 5, 'Scarf': 4},
            Effect={'Sparks': 5, 'Rain': 4},
        )),
]

# unicatele fiecarui lot
UNIQUES = {
    'GEN':  [('Patient Zero', dict(suit='OG Yellow', eye='Red', hat=None, item=None,
                                   cloth=None, scene='Studio Teal', fx=None, badge='OG Patch', crest='OG Black', neck=None, shoe='OG Pink', glove='Grey Mitts')),
             ('Blank Slate', dict(suit='Chalk', eye='Void', hat=None, item=None,
                                  cloth=None, scene='Void', fx=None, badge='Serial Tag', crest='Chrome', neck=None, shoe='Void Black', glove='Black Tactical'))],
    'DEEP': [('Absolute Zero', dict(mat='Frozen', eye='Ice Blue', hat=None, item='Diamond',
                                    cloth='Cape', scene='Ice Cave', fx='Snow', badge=None, crest='Neon Cyan', neck=None, shoe='Steel Toe', glove='Bone')),
             ('The Trench', dict(suit='Cobalt', eye='Cyan', hat='Space Dome', item='Trident',
                                 cloth='Backpack', scene='Deep Sea', fx='Bubbles', badge='Serial Tag', crest='Chrome', neck='Cable Rig', shoe='Steel Toe', glove='Black Tactical'))],
    'NEON': [('Signal Lost', dict(mat='Glitched', eye='Violet', hat='Headphones', item='Spray Can',
                                  cloth='Puffer Jacket', scene='Neon Alley', fx='Glitch', badge='Cracked Panel', crest='Neon Pink', neck='Cable Rig', shoe='Neon Sole', glove='Neon Glow')),
             ('Midnight Mayor', dict(mat='Neon Wire', eye='Cyan', hat='Top Hat', item='Chain',
                                     cloth='Gold Chains', scene='Rooftop Night', fx='Scanlines', badge=None, crest='Gold Wire', neck='Medallion', shoe='Gold Kicks', glove='Gold Gauntlet'))],
    'PIT':  [('Meltdown', dict(mat='Molten', eye='Amber', hat='Flames', item='Torch',
                               cloth=None, scene='Lava Field', fx='Embers', badge='Radiation', crest='Spikes', neck=None, shoe='Steel Toe', glove='Rust Plate')),
             ('Deep Shaft', dict(mat='Rusted', eye='Red', hat='Hard Hat', item='Lantern',
                                 cloth='Tool Belt', scene='Mine Shaft', fx=None, badge='Cracked Panel', crest='OG Black', neck='Dog Tags', shoe='Work Boots', glove='Rust Plate'))],
    'CNCL': [('The Sovereign', dict(mat='Solid Gold', eye='Gold', hat='Crown', item='Arcane Staff',
                                    cloth='Cape', scene='Void', fx=None, badge='OG Patch', crest='Gold Wire', neck='Medallion', shoe='Gold Kicks', glove='Gold Gauntlet')),
             ('House Always Wins', dict(suit='Ink', eye='Gold', hat='Top Hat', item='Money Bag',
                                        cloth='Tuxedo', scene='Casino Floor', fx=None, badge=None, crest='OG Black', neck='Medallion', shoe='Void Black', glove='Black Tactical'))],
    'FLD':  [('The Botanist', dict(mat='Overgrown', eye='Acid Green', hat='Straw Hat', item='Shovel',
                                   cloth='Apron', scene='Greenhouse', fx=None, badge=None, crest='Acid', neck='Bone Lei', shoe='Work Boots', glove='Bone')),
             ('Canopy', dict(suit='Moss', eye='Amber', hat='Pith Helmet', item='Umbrella',
                             cloth='Backpack', scene='Jungle Temple', fx='Rain', badge=None, crest='Acid', neck='Bone Lei', shoe='Work Boots', glove='Rust Plate'))],
    'CLN':  [('Ghost in the Wire', dict(mat='Matrix Code', eye='Acid Green', hat=None, item=None,
                                        cloth=None, scene='Matrix Rain', fx='Glitch', badge='Circuit Plate', crest='Acid', neck='Cable Rig', shoe='Neon Sole', glove='Neon Glow')),
             ('Sample 001', dict(suit='Bone White', eye='Ice Blue', hat='Space Dome', item='Flask',
                                 cloth='Lab Coat', scene='Toxic Lab', fx='Radiation', badge='Biohazard', crest='Chrome', neck='Dog Tags', shoe='White Sneakers', glove='Bone'))],
    'WAR':  [('The Cyber-Samurai', dict(suit='Blood Red', eye='Violet', hat='Kabuto', item='Katana',
                                        cloth='Armor', scene='Cyber Grid', fx=None, badge=None, crest='Spikes', neck='Dog Tags', shoe='Red Runners', glove='Gold Gauntlet')),
             ('Last Raider', dict(suit='Void Black', eye='Red', hat='Viking Helm', item='Scythe',
                                  cloth='Cape', scene='Wasteland', fx='Embers', badge='Cracked Panel', crest='Mohawk', neck='Dog Tags', shoe='Work Boots', glove='Black Tactical'))],
    'OFF':  [('Null Pointer', dict(mat='Circuit', eye='Void', hat='Beacon', item='Chain',
                                   cloth=None, scene='Void', fx='Scanlines', badge='Circuit Plate', crest='Neon Cyan', neck='Cable Rig', shoe='Void Black', glove='Neon Glow')),
             ('Deep Space Drift', dict(mat='Cosmic', eye='Cyan', hat='Space Dome', item='Diamond',
                                       cloth=None, scene='Orbital Deck', fx='Sparks', badge=None, crest='Antennae', neck=None, shoe='Steel Toe', glove='Bone'))],
    'AFT':  [('Last Call', dict(suit='Bubblegum', eye='Violet', hat='Party Hat', item='Guitar',
                                cloth='Hawaiian Shirt', scene='Arcade', fx='Sparks', badge='Heart', crest='Neon Pink', neck='Bone Lei', shoe='Court Green', glove='Neon Glow')),
             ('High Roller', dict(suit='Denim', eye='Gold', hat='Cowboy Hat', item='Money Bag',
                                  cloth='Gold Chains', scene='Casino Floor', fx=None, badge='OG Patch', crest='Gold Wire', neck='Medallion', shoe='Gold Kicks', glove='Gold Gauntlet'))],
}
